export const Render2DEnum = {
    ORIGIN_TOP:          "RENDER2D_ORIGIN_TOP",
    ORIGIN_TOP_RIGHT:    "RENDER2D_ORIGIN_TOP_RIGHT",
    ORIGIN_RIGHT:        "RENDER2D_ORIGIN_RIGHT",
    ORIGIN_BOTTOM_RIGHT: "RENDER2D_ORIGIN_BOTTOM_RIGHT",
    ORIGIN_BOTTOM:       "RENDER2D_ORIGIN_BOTTOM",
    ORIGIN_BOTTOM_LEFT:  "RENDER2D_ORIGIN_BOTTOM_LEFT",
    ORIGIN_LEFT:         "RENDER2D_ORIGIN_LEFT",
    ORIGIN_TOP_LEFT:     "RENDER2D_ORIGIN_TOP_LEFT",
    ORIGIN_CENTER:       "RENDER2D_ORIGIN_CENTER",
};